# docker-compose.yml
services:
  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    profiles: ["redis"]

  chroma:
    image: chromadb/chroma:0.6.4.dev412
    ports:
      - "8000:8000"
    profiles: ["chroma"]

  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      QUERY_DEFAULTS_LIMIT: "25"
    restart: unless-stopped
    profiles: ["weaviate"]
